import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Grid from '@mui/material/Grid';
import Box from '@mui/material/Box';
import Page from "@/app/dashboard/page";




import Header from "@/components/header/page";
import CssBaseline from '@mui/material/CssBaseline';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <Box sx={{ display: 'flex',minHeight: '100vh' }}>
            <CssBaseline />
            <Header />
             {children}
        </Box>
        
       
               
          
      </body>
    </html>
    
  );
}
